version: '3'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5433; do sleep 1; done; python manage.py runserver 0.0.0.0:8009'
    volumes:
      - .:/app
    ports:
      - "8009:8009"
    depends_on:
      - db
    links: 
      - db:db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres_data:
