version: '3'

services:
  attendance-db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    

  web:
    build: .
    command: bash -c 'while !</dev/tcp/attendance-db/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8009'
    volumes:
      - .:/app
    ports:
      - "8009:8009"
    depends_on:
      - attendance-db
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=attendance-db
      - DATABASE_PORT=5432


volumes:
  postgres_data:
