# Generated by Django 4.2.13 on 2024-06-10 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data da aula')),
                ('attendance', models.BooleanField(blank=True, null=True, verbose_name='Presença do aluno')),
                ('class_type', models.CharField(blank=True, choices=[('an', 'Aula normal'), ('ar', 'Aula reposição')], max_length=2, null=True, verbose_name='Tipo de Aula')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
