# Generated by Django 4.2.13 on 2024-06-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecorder',
            name='course_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Id do curso'),
        ),
    ]
