# Generated by Django 4.2.13 on 2024-06-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attendancerecorder_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecorder',
            name='user',
        ),
        migrations.AddField(
            model_name='attendancerecorder',
            name='students_presents',
            field=models.TextField(null=True),
        ),
    ]
