# Generated by Django 4.2.13 on 2024-06-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_attendancerecorder_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecorder',
            name='students_presents',
        ),
        migrations.AddField(
            model_name='attendancerecorder',
            name='students_attendance',
            field=models.JSONField(blank=True, default=None, max_length=2000, null=True),
        ),
    ]
